name: Update Registry

on:
  push:
    branches: [master]

jobs:
  build:
    uses: visavi/rotor-modules/.github/workflows/update-registry.yml@master
    with:
      registry-name: Official Rotor Languages
    permissions:
      contents: write